#!/bin/sh
DIR="`basename $(pwd)`"

if [ -f name ]
then
	echo '\chapter{'`cat name`'}' > index.tex
else
	echo '\chapter{'$DIR'}' > index.tex
fi

echo '\begin{multicols}{2}' >> index.tex
for FILE in "$@"
do
	echo '\input{'$DIR/$FILE'}' >> index.tex
done
echo '\end{multicols}' >> index.tex
