#!/bin/bash
DIR="`basename $(pwd)`"

if [ -f name ]
then
	echo '\chapter{'`cat name`'}' > index.tex
else
	echo '\chapter{'$DIR'}' > index.tex
fi

echo '\begin{multicols}{2}\raggedcolumns' >> index.tex
for FILE in $(ls *.tex | egrep -v 'index.tex' | sed -e 's/\.tex$//' | sort | sed -e 's/$/.tex/')
do
	echo '\importrcp{'rcp:$DIR:$(basename $FILE .tex)'}{'$DIR/$FILE'}' >> index.tex
done
echo '\end{multicols}' >> index.tex
