#!/bin/sh

for each in */*.tex
do
	for expr in '([0-9]|\\(|two|three)(third|quarter|eighth)) (minute|hour|second|day|week)' '[0-9](| |\\,|~)(cm|oz|lbs)' '[0-9]+ \\(|two|three)(third|quarter|eighth)' '\\(|two|three)(third|quarter|eighth) +[^\\]' '\\textdegree' 'cup' '[Tt]b?sp' '(tea|table)spoon' '[pP]re-heat' '[lL]iquor'
	do
		lines="`egrep -n "$expr" $each | cut -f 1 -d : | tr '\n' ' '`"
		[ ! -z "$lines" ] && echo $each fails $expr on $lines
	done
done
