#!/bin/sh

for each in $(./indexedingredients | sed -e 's/ /+/g;s/^\(.*\)!\(.*\)/\2#\1/g'
)
do
	theme="\\<$(echo $each | sed -e 's/+/ /g;s/#/( |}{)/g')\\>"
	echo "#$each"
	./filteringredients "$@" | tr '~' '_' | awk -F: '$1 != curfile {curfile = $1; process = 1} process {} $2 ~ /'"$theme"'/ && $2 ~ /theme/ { process = 0; } process && $2 ~ /'"$theme"'/ { print $0; process = 0}'
done

